### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by 3DSmitty** [makerbase-mks/MKS-SERVO42B#1]
I would like to know the source code is available for upgrades before I purchase them.

**Comment by GsmZolika** [comment]
Hi! Can I have firmware for 42B board? I'm kill the stm32 cpu. I have a new cpu. 
Thanks!

**Comment by makerbase-mks** [comment]
@3DSmity @GsmZolika
We have put how to compile the firmware, upload the firmware tutorial in Readme, please see

**Comment by makerbase-mks** [comment]
@3DSmity @GsmZolika
Hey buddy. You can refer to: https://github.com/makerbase-mks/MKS-SERVO42B/tree/master/firmware
This is Source code and provide how to build it and uopload it and so on.

**Comment by 3DSmitty** [comment]
THANKS!
