### ISSUE TITLE
Marlin configuration

### ISSUE THREAD

**Issue by calabia2000** [makerbase-mks/MKS-SERVO42B#13]
I have bought this article (it has not reached me yet), in marlin 2.0 you must define the type of driver used (a4988, tmcxxx, etc).  Using this servo42b what type of driver should I define in marlin 2.0

**Comment by makerbase-mks** [comment]
You don't need to define it, you can use it directly.

**Comment by ghent360** [comment]
Use the default a4988 driver with no special current control. That is what the previous comment meant - you don't have to change the driver the default just works.

You have to match the microsteps in the Marlin configuration with the servo configuration. I believe the default is 16 on both.

**Comment by 3DMadeUp** [comment]
Sorry, i buy the mks servo42b but i have more noise on y axis when change direction........why??
Thanks for help, i just try the marlin configuration
