### ISSUE TITLE
Can you add BOM?

### ISSUE THREAD

**Issue by dzid26** [makerbase-mks/MKS-SERVO42B#14]
Can you add BOM to go along the schematics to understand the board operation better?

**Comment by ramonbastos** [comment]
Can you add BOM to schematics?

**Comment by makerbase-mks** [comment]
Hi! You can refer to https://github.com/makerbase-mks/MKS-SERVO42B/blob/master/hardware/MKS%20SERVO42B%20V1.0_003/MKS%20SERVO42B%20V1.0_003%20BOM.pdf
