### ISSUE TITLE
Update wiki with ST-link isntruction to disable "Read Out Protection"

### ISSUE THREAD

**Issue by dzid26** [makerbase-mks/MKS-SERVO42B#17]
Error when trying to connect to STM32:
```
Can not read memory!
Disable Read Out Protection and retry.
```

1. In order to unprotect the chip with [ST-LINK](https://www.st.com/en/development-tools/stsw-link004.html), one has to click _Target_ -> _Option Bytes_:
-> change **_Read-Out Protection_** - **Disabled**. 
![image](https://user-images.githubusercontent.com/841061/89252621-467dcd00-d5e8-11ea-9438-e46b55fb43fd.png)

2. Then it is possible to switch to System memory (0x1FFFF800) and see firmware binary:
![image](https://user-images.githubusercontent.com/841061/89253072-90b37e00-d5e9-11ea-8e03-cfb6a5624e75.png)

3. Flashing is possible now.

**Comment by makerbase-mks** [comment]
Hi! You need Unsecure chip by J flash or other tool, but i know't your tool hold Unsecure chip function.
![image](https://user-images.githubusercontent.com/12979070/89360630-9e592880-d6fb-11ea-8326-0111754d04b1.png)

**Comment by dzid26** [comment]
I know.
I provided solution for ST-link, because it was not obvious what to do. 
You can add my instruction to the wiki https://github.com/makerbase-mks/MKS-SERVO42B/wiki/MKS-SERVO42B-User-Manual#how-to-upload-firmware so it's easier for people understand how to do it with ST-Link tool.

**Comment by mustafaergul0** [comment]
In section Read Out Protection, it says Level0, Level1, Level2.
How can I turn off Read Out Protection

**Comment by dzid26** [comment]
> In section Read Out Protection, it says Level0, Level1, Level2. How can I turn off Read Out Protection

This doesn't work for you?
https://github.com/makerbase-mks/MKS-SERVO42B/issues/17#issue-672503790

**Comment by mustafaergul0** [comment]
unfortunately not working. When I try to change from Level 1 to Level 0 I get error "Could not set Options byte! Please reset the target and retry"

**Comment by fpvmate** [comment]
> unfortunately not working. When I try to change from Level 1 to Level 0 I get error "Could not set Options byte! Please reset the target and retry"

I also get same error did anyone solved this ?

**Comment by dzid26** [comment]
> > unfortunately not working. When I try to change from Level 1 to Level 0 I get error "Could not set Options byte! Please reset the target and retry"
> 
> I also get same error did anyone solved this ?

The first post says what to do.

**Comment by fpvmate** [comment]
> > > unfortunately not working. When I try to change from Level 1 to Level 0 I get error "Could not set Options byte! Please reset the target and retry"
> > 
> > 
> > I also get same error did anyone solved this ?
> 
> The first post says what to do.

I tried that and it didn't work that's why asked again.

**Comment by up2smoke** [comment]
+1 disable protection is nt possible

**Comment by dzid26** [comment]
> In section Read Out Protection, it says Level0, Level1, Level2. How can I turn off Read Out Protection
I had a look at it again. F103 series chip doesn't have protection _levels_. Only _disabled/enabled_ options. So you are writing in the wrong Github issue or maybe somehow you were debugging wrong target.
This should be reported device:
![image](https://user-images.githubusercontent.com/841061/157485353-77b484c2-66e8-404d-9413-6308ce8fd52f.png)

**Comment by fpvmate** [comment]
> > In section Read Out Protection, it says Level0, Level1, Level2. How can I turn off Read Out Protection
> > I had a look at it again. F103 series chip doesn't have protection _levels_. Only _disabled/enabled_ options. So you are writing in the wrong Github issue or maybe somehow you were debugging wrong target.
> > This should be reported device:
> > ![image](https://user-images.githubusercontent.com/841061/157485353-77b484c2-66e8-404d-9413-6308ce8fd52f.png)

But what about stm32f405 chips in that while I was using in my flight controller the board stopped responding and when i connect the processor with st-link it's saying read out protection is enabled and when i try to make it to level 0 it's not happening and says failed in between . Any solution for that or is it possible to erase the entire chip ? Can anything be done with the help of boot pins of the processor?

**Comment by dzid26** [comment]
If it is set to Level2 then it is irreversible. https://www.st.com/resource/en/application_note/an4701-proprietary-code-readout-protection-on-microcontrollers-of-the-stm32f4-series-stmicroelectronics.pdf 
Anyway, your problem doesn't belong to this issue.

**Comment by Sasha7b9Work** [comment]
This helped me: https://community.st.com/s/question/0D50X00009Xkdy5SAB/not-able-to-update-option-bytes
(update firmware  ST-Link utility)

**Comment by huanbaose** [comment]
> 在读取保护部分中，它显示 Level0、Level1、Level2。 如何关闭读出保护

You need to select Level0.

**Comment by mfaghani** [comment]
> unfortunately not working. When I try to change from Level 1 to Level 0 I get error "Could not set Options byte! Please reset the target and retry"

I've had the same problem with ST-LINK and STM32 ST-LINK Utility V 4.6.0.0, it was solved by decreasing the connection frequency from 4MHz to 125KHz in Target->Settings->Connection Settings.
