### ISSUE TITLE
OLED and A1333 SPI port circuit design

### ISSUE THREAD

**Issue by RepRapThailand** [makerbase-mks/MKS-SERVO42B#24]
Hi,

I wonder if it can be designed to keep the OLED and A1333 on the same SPI port. Why did you separate design as SPI1 and SPI2?

Regards,

**Comment by mks-viva** [comment]
Hi! Distinguish them, easier to operate, without considering the compatibility of the two and switching operations back and forth.

**Comment by mks-viva** [comment]
If you have better suggestions, we will also refer to them. I will close this issues temporarily
