### ISSUE TITLE
[.pio/build/mks_servo42b/firmware.elf] Error 1

### ISSUE THREAD

**Issue by medchedli** [makerbase-mks/MKS-SERVO42B#29]
Hello 

When building the project I get this error that I couldn't figure how to debug it 

Indexing .pio/build/mks_servo42b/libFrameworkCMSISDevice.a
Linking .pio/build/mks_servo42b/firmware.elf
.pio/build/mks_servo42b/src/LIB/src/stm32f10x_flash.o: In function `FLASH_WaitForLastOperation':
/home/medchedli/Documents/MKS-SERVO42B/firmware/src/LIB/src/stm32f10x_flash.c:1596: multiple definition of `FLASH_WaitForLastOperation'
.pio/build/mks_servo42b/FrameworkHALDriver/Src/stm32f1xx_hal_flash.o:/home/medchedli/.platformio/packages/framework-stm32cubef1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c:827: first defined here
.pio/build/mks_servo42b/libFrameworkCMSISDevice.a(system_stm32f1xx.o): In function `SystemInit':
/home/medchedli/.platformio/packages/framework-stm32cubef1/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/system_stm32f1xx.c:188: multiple definition of `SystemInit'
.pio/build/mks_servo42b/src/CMSIS/system_stm32f10x.o:/home/medchedli/Documents/MKS-SERVO42B/firmware/src/CMSIS/system_stm32f10x.c:216: first defined here
.pio/build/mks_servo42b/libFrameworkCMSISDevice.a(system_stm32f1xx.o): In function `SystemCoreClockUpdate':
/home/medchedli/.platformio/packages/framework-stm32cubef1/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/system_stm32f1xx.c:238: multiple definition of `SystemCoreClockUpdate'
.pio/build/mks_servo42b/src/CMSIS/system_stm32f10x.o:/home/medchedli/Documents/MKS-SERVO42B/firmware/src/CMSIS/system_stm32f10x.c:319: first defined here
.pio/build/mks_servo42b/libFrameworkCMSISDevice.a(system_stm32f1xx.o):(.rodata.AHBPrescTable+0x0): multiple definition of `AHBPrescTable'
.pio/build/mks_servo42b/src/CMSIS/system_stm32f10x.o:/home/medchedli/Documents/MKS-SERVO42B/firmware/src/CMSIS/system_stm32f10x.c:167: first defined here
.pio/build/mks_servo42b/libFrameworkCMSISDevice.a(system_stm32f1xx.o):(.data.SystemCoreClock+0x0): multiple definition of `SystemCoreClock'
.pio/build/mks_servo42b/src/CMSIS/system_stm32f10x.o:(.data.SystemCoreClock+0x0): first defined here
collect2: error: ld returned 1 exit status
*** [.pio/build/mks_servo42b/firmware.elf] Error 1`
`

![image](https://user-images.githubusercontent.com/3912825/112670540-52f9b300-8e61-11eb-8bd7-e2ed23d6c147.png)

**Comment by medchedli** [comment]
I replaced ststm version with an older one (11.0.0) and It did fix the problem. There is many declaration conflicts with ststm latest release ( version 12.0.0)

**Comment by mks-viva** [comment]
Hi! I has fix it
![image](https://user-images.githubusercontent.com/16629551/112929145-731fbf80-914a-11eb-9cc4-2625cbf49b7f.png)
