### ISSUE TITLE
Please Provide binary Images of the firmware

### ISSUE THREAD

**Issue by wildblue** [makerbase-mks/MKS-SERVO42B#4]
I need servo42B v1.0 original Firmware, to revert this version you Provider. It is Not the same software

**Comment by makerbase-mks** [comment]
Can you provide me with a mailbox? I send the source code to you, just to compile the platform using Keil.

**Comment by wildblue** [comment]
I sent an email to 4164049@qq.com with my requests for the compiled binary. It would be simpler If you Just include the Files on GitHub.

**Comment by makerbase-mks** [comment]
Currently github projects can be compiled and used normally

**Comment by zhangqin112** [comment]
能否给我提供一份42B v1.0原源代码（用于使用Keil编译平台），我的邮箱517794972@qq.com。谢谢
