### ISSUE TITLE
Error displaying small errors.

### ISSUE THREAD

**Issue by lonelymyp** [makerbase-mks/MKS-SERVO42B#5]
If the error in the negative direction is less than 1 degree, the minus sign is not displayed

Example:
0.97 err
0.98 err
0.99 err
-1.00 err
-1.01 err
-1.02 err

How it should be:
-0.97 err
-0.98 err
-0.99 err
-1.00 err
-1.01 err
-1.02 err

**Comment by makerbase-mks** [comment]
After this issue needs to be verified, we fix it. Of course, you can also modify the code according to your ideas, optimize together.

**Comment by makerbase-mks** [comment]
Hi! I has fix it. You can refer to new firmware and update it to servo42b.
