### ISSUE TITLE
driver overheating

### ISSUE THREAD

**Issue by lonelymyp** [makerbase-mks/MKS-SERVO42B#6]
If you set a current of 900 mA or higher, then the driver overheats already during the calibration process.
Driver temperature reaches 120 degrees

**Comment by makerbase-mks** [comment]
Hi!
1. Increase the installation of heat sinks, and the heat dissipation will be further improved.
2. Does your motor need a load of 900ma?
3. Do you have any good suggestions for further optimization of SERVO42B.

**Comment by lonelymyp** [comment]
3. The motor driver must be installed on the other side of the board. So that you can stick a small radiator to the heat sink area. 
so for example, done in the drivers tmc2208 
![image](https://user-images.githubusercontent.com/2085051/72750108-f94a8880-3bcc-11ea-9f38-d5a702b98619.png)

**Comment by makerbase-mks** [comment]
This seems pretty good.

**Comment by wildblue** [comment]
Put a small thermal compound pad between the motor and the pcb, right below the driver-ic. This should dissipate the heat in the aluminium body of the servo.

**Comment by makerbase-mks** [comment]
We will consider this.

**Comment by dzid26** [comment]
What was the point of the [1500 offset](https://github.com/makerbase-mks/MKS-SERVO42B/blob/5328f04baca6f2080d3ea97f9990e5f72c244413/firmware/src/BSP/A4950.c#L122) that is present on both coils at all times ?!!

Edit: offset is super small compared to the mA*sin, so it doesn't really matter.

**Comment by lonelymyp** [comment]
@dzid26 
> What was the point of the offset?!!

This bug appeared when they copied the code of the original nano stepper.
If you want it to work correctly, you need to change the code like the original.
https://github.com/Misfittech/nano_stepper/blob/master/firmware/stepper_nano_zero/A5995.cpp

**Comment by dzid26** [comment]
It worked even with the offset, but slightly less torque and slightly more heat. 

Apart from that, I don't see any fundamental issues with the implementation.
